# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'x.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(400, 360)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(400, 360))
        MainWindow.setMaximumSize(QtCore.QSize(400, 360))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(26, 26, 46);\n"
"color: rgb(242, 242, 242);\n"
"font: 8pt \"Ubuntu Condensed\";\n"
"font-weight: bold;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 0, 381, 321))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(6, 6, 6, 6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(12, 6, 12, 6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.enterURLLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.enterURLLabel.setObjectName("enterURLLabel")
        self.verticalLayout_2.addWidget(self.enterURLLabel)
        self.urlTextBox = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.urlTextBox.setMinimumSize(QtCore.QSize(0, 25))
        self.urlTextBox.setStyleSheet("background-color: rgb(15, 52, 96);\n"
"font: 8pt \"Ubuntu Condensed\";\n"
"padding-left: 10px;\n"
"padding-right: 10px;\n"
"padding-top:5px;\n"
"padding-bottom: 5px;\n"
"font-weight: bold;")
        self.urlTextBox.setObjectName("urlTextBox")
        self.verticalLayout_2.addWidget(self.urlTextBox)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(6, -1, 6, 6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.changeFileNameLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.changeFileNameLabel.setObjectName("changeFileNameLabel")
        self.verticalLayout_3.addWidget(self.changeFileNameLabel)
        self.newFileName = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.newFileName.setMinimumSize(QtCore.QSize(0, 25))
        self.newFileName.setStyleSheet("background-color: rgb(15, 52, 96);\n"
"font: 8pt \"Ubuntu Condensed\";\n"
"padding-left: 10px;\n"
"padding-right: 10px;\n"
"padding-top:5px;\n"
"padding-bottom: 5px;\n"
"font-weight: bold;")
        self.newFileName.setObjectName("newFileName")
        self.verticalLayout_3.addWidget(self.newFileName)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.savePathLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.savePathLabel.setObjectName("savePathLabel")
        self.verticalLayout.addWidget(self.savePathLabel)
        self.savePath = QtWidgets.QLabel(self.gridLayoutWidget)
        self.savePath.setObjectName("savePath")
        self.verticalLayout.addWidget(self.savePath)
        self.selectPathButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.selectPathButton.setStyleSheet("background-color: rgb(233, 69, 96);\n"
"font: 8pt \"Ubuntu Condensed\";\n"
"font-weight: bold;")
        self.selectPathButton.setObjectName("selectPathButton")
        self.verticalLayout.addWidget(self.selectPathButton)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.fileInformationsFormLayout = QtWidgets.QFormLayout()
        self.fileInformationsFormLayout.setContentsMargins(12, 6, 12, 6)
        self.fileInformationsFormLayout.setObjectName("fileInformationsFormLayout")
        self.fileSizeLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.fileSizeLabel.setObjectName("fileSizeLabel")
        self.fileInformationsFormLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.fileSizeLabel)
        self.downloadSpeedLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.downloadSpeedLabel.setObjectName("downloadSpeedLabel")
        self.fileInformationsFormLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.downloadSpeedLabel)
        self.fileSize = QtWidgets.QLabel(self.gridLayoutWidget)
        self.fileSize.setObjectName("fileSize")
        self.fileInformationsFormLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fileSize)
        self.downloadSpeed = QtWidgets.QLabel(self.gridLayoutWidget)
        self.downloadSpeed.setObjectName("downloadSpeed")
        self.fileInformationsFormLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.downloadSpeed)
        self.downloadPercentageLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.downloadPercentageLabel.setObjectName("downloadPercentageLabel")
        self.fileInformationsFormLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.downloadPercentageLabel)
        self.DownloadPercentage = QtWidgets.QLabel(self.gridLayoutWidget)
        self.DownloadPercentage.setObjectName("DownloadPercentage")
        self.fileInformationsFormLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.DownloadPercentage)
        self.downloadedBytesLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.downloadedBytesLabel.setObjectName("downloadedBytesLabel")
        self.fileInformationsFormLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.downloadedBytesLabel)
        self.downloadedBytes = QtWidgets.QLabel(self.gridLayoutWidget)
        self.downloadedBytes.setObjectName("downloadedBytes")
        self.fileInformationsFormLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.downloadedBytes)
        self.statusLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.statusLabel.setObjectName("statusLabel")
        self.fileInformationsFormLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.statusLabel)
        self.status = QtWidgets.QLabel(self.gridLayoutWidget)
        self.status.setObjectName("status")
        self.fileInformationsFormLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.status)
        self.gridLayout_2.addLayout(self.fileInformationsFormLayout, 4, 0, 1, 1)
        self.downloadButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.downloadButton.setStyleSheet("background-color: rgb(233, 69, 96);\n"
"font: 8pt \"Ubuntu Condensed\";\n"
"font-weight: bold;")
        self.downloadButton.setObjectName("downloadButton")
        self.gridLayout_2.addWidget(self.downloadButton, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Video Downloader"))
        self.enterURLLabel.setText(_translate("MainWindow", "Enter a URL:"))
        self.urlTextBox.setPlaceholderText(_translate("MainWindow", "URL"))
        self.changeFileNameLabel.setText(_translate("MainWindow", "Change File Name:"))
        self.newFileName.setPlaceholderText(_translate("MainWindow", "Enter a new file name"))
        self.savePathLabel.setText(_translate("MainWindow", "Default Save Path:"))
        self.savePath.setText(_translate("MainWindow", "-"))
        self.selectPathButton.setText(_translate("MainWindow", "Select Path"))
        self.fileSizeLabel.setText(_translate("MainWindow", "File Size:"))
        self.downloadSpeedLabel.setText(_translate("MainWindow", "Download Speed:"))
        self.fileSize.setText(_translate("MainWindow", "0"))
        self.downloadSpeed.setText(_translate("MainWindow", "0"))
        self.downloadPercentageLabel.setText(_translate("MainWindow", "Download Percentage:"))
        self.DownloadPercentage.setText(_translate("MainWindow", "0%"))
        self.downloadedBytesLabel.setText(_translate("MainWindow", "Downloaded:"))
        self.downloadedBytes.setText(_translate("MainWindow", "0"))
        self.statusLabel.setText(_translate("MainWindow", "Status:"))
        self.status.setText(_translate("MainWindow", "-"))
        self.downloadButton.setText(_translate("MainWindow", "Download"))
        
import resources_rc
